classes:
  statsclient:
  web::server:
    vhost: youtube.adblockplus.me
    certificate: youtube.adblockplus.me_sslcert.pem
    private_key: youtube.adblockplus.me_sslcert.key
    is_default: true
    repository: youtube.adblockplus.me

