classes:
  adblockplus::web::redirector:
    domain: "eyeo.to"
    default: "https://eyeo.com/"

adblockplus::web::redirector::targets:
  acceptableads: "https://acceptableads.com/"
  adblockbrowser: "https://adblockbrowser.org/"
  adblockbrowser/android: "https://play.google.com/store/apps/details?id=org.adblockplus.browser"
  adblockbrowser/ios: "https://itunes.apple.com/app/adblock-browser-best-ad-blocker/id1015653330"
  adblockplus: "https://adblockplus.org/"
  badadssuck: "https://itunes.apple.com/app/adblock-browser/id1015653330"
  flattr: "https://flattr.com/"
  flattr-publishers: "https://flattr.com/publishers"
  jobs: "https://eyeo.com/en/jobs"
  team: "https://eyeo.com/en/team"
  adblockplus/privacy_friendly_ads: "https://adblockplus.org/acceptable-ads#privacy-friendly-acceptable-ads?"
  adblockplus/credits: "https://adblockplus.org/contributors"
  adblockplus/contributors: "https://adblockplus.org/contributors?"
  adblockplus/reporter_connect_issue: "https://adblockplus.org/forum/?"
  adblockplus/reporter_other_link: "https://adblockplus.org/forum/?"
  adblockplus/firefox_support: "https://adblockplus.org/forum/viewforum.php?f=1?"
  adblockplus/chrome_support: "https://adblockplus.org/forum/viewforum.php?f=10?"
  adblockplus/opera_support: "https://adblockplus.org/forum/viewforum.php?f=14?"
  adblockplus/safari_support: "https://adblockplus.org/forum/viewforum.php?f=18?"
  adblockplus/edge_support: "https://adblockplus.org/forum/viewforum.php?f=27?"
  adblockplus/knownIssuesChrome_filterstorage: "https://adblockplus.org/forum/viewtopic.php?t=23597?"
  adblockplus/firefox_support: "https://adblockplus.org/forum/viewforum.php?f=1?"
  adblockplus/adblock_browser_android_beta_community: "https://plus.google.com/communities/104936844759781288661?"
  adblockplus/adblock_browser_android_support: "https://adblockplus.org/forum/viewforum.php?f=24?"
  adblockplus/adblock_browser_android_faq: "https://adblockplus.org/forum/viewforum.php?f=24?"
  adblockplus/adblock_browser_ios_support: "https://adblockplus.org/forum/viewforum.php?f=25?"
  adblockplus/adblock_browser_ios_store: "https://geo.itunes.apple.com/us/app/adblock-browser-best-ad-blocker/id1015653330?mt=8?"
  adblockplus/adblock_plus_safari_ios_support: "https://adblockplus.org/forum/viewforum.php?f=26?"
  adblockplus/adblock_plus_safari_ios_store: "https://itunes.apple.com/app/adblock-plus-abp/id1028871868?"
  adblockplus/adblock_plus_sbrowser_store: "https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser?"
  adblockplus/adblock_plus_chrome_dnt: "https://support.google.com/chrome/answer/2790761?"
  adblockplus/adblock_plus_firefox_dnt: "https://www.mozilla.org/en-US/firefox/dnt/?"
  adblockplus/adblock_plus_opera_dnt: "http://help.opera.com/Windows/12.10/en/notrack.html?"
  adblockplus/adblock_plus_edge_dnt: "https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy?"
  adblockplus/adblock_plus_report_bug: "https://adblockplus.org/bugs#reporting?"
  adblockplus/adblock_plus_report_ad: "https://forums.lanik.us/viewforum.php?f=62?"
  adblockplus/releases: "https://adblockplus.org/releases?"
  adblockplus/social_facebook: "https://www.facebook.com/adblockplus?"
  adblockplus/social_gplus: "https://www.google.com/+AdblockPlus?"
  adblockplus/social_renren: "http://www.renren.com/601651969?"
  adblockplus/social_twitter: "https://twitter.com/adblockplus?"
  adblockplus/social_weibo: "http://e.weibo.com/adblockplus/?"

