classes:
  adblockplus::web::redirector:
    domain: "eyeo.to"
    default: "https://eyeo.com/"

adblockplus::web::redirector::targets:
  acceptableads: "https://acceptableads.com/"
  adblockbrowser: "https://adblockbrowser.org/"
  adblockplus: "https://adblockplus.org/"
  badadssuck: "https://itunes.apple.com/app/adblock-browser/id1015653330"
  flattr: "https://flattr.com/"
  flattr-publishers: "https://flattr.com/publishers"
  jobs: "https://eyeo.com/en/jobs"
  team: "https://eyeo.com/en/team"
  adblockplus/privacy_friendly_ads: "https://adblockplus.org/acceptable-ads#privacy-friendly-acceptable-ads"

