classes:
  statsclient:
  downloadserver:
    domain: downloads.adblockplus.org
    certificate: downloads.adblockplus.org_sslcert.pem
    private_key: downloads.adblockplus.org_sslcert.key
    is_default: true

