classes:
  adblockplus::legacy::filterserver:
  notificationserver:
    is_default: false

filterserver::is_default: true

# http://hub.eyeo.com/issues/1981
nginx::worker_connections: 4000
nginx::ssl_session_cache: off

# http://hub.eyeo.com/issues/1990
nginx::modules:
  geoip:
    name: "ngx_http_geoip_module.so"

geoip::hook: 'systemctl reload nginx.service'

